### ISSUE TITLE
identify the right worker for the job

### ISSUE THREAD

**Issue by dharmjit** [chiefnoah/goalpost#1]
Hi, I was browsing this project and found it simple and minimal. I guess currently If I have multiple workers, the queue.go **registerWorker** implementation doesn't take into account jobId- worker relation.Let me know If my understanding is correct.

**Comment by dharmjit** [comment]
I understand from this blog post https://dev.to/chiefnoah/goalpost-a-durable-embeddable-worker-queue-for-golang-13ok that we can register only a single type of worker. Is it true

**Comment by chiefnoah** [comment]
>  the queue.go registerWorker implementation doesn't take into account jobId- worker relation.Let me know If my understanding is correct.

Correct, the worker id is meant to be used for logging purposes and is not used to schedule a job to be handled by a specific worker.

> we can register only a single type of worker. Is it true

Yes and no. You can register different implementations of the `Worker` interface to the same `Queue` instance, but you have no way of controlling which implementation gets used for a given job. I can't think of any practical cases where you would register different implementations on the same `Queue`, but maybe someone has a usecase for that. If you need to have different types of `Job`s go to different `Worker`s, create a `Queue` for the different types and register your `Worker`s appropriately.

**Comment by dharmjit** [comment]
Hi @chiefnoah Thanks for responding on this. My use case is, I have micro services architecture and one service has jobs for different micro services where business logic will be different. So I am thinking of different worker implementation. The way I have achieved it as of now is by defining a custom jobChan

```
type jobChan struct {
	jobId      int32
	workerName string
}

// Queue represents a queue
type Queue struct {
	//ID is a unique identifier for a Queue
	ID string
	//db represents a handle to a bolt db
	db *sql.DB
	//notifier is a chan used to signal workers there is a job to begin working
	notifier chan jobChan
	//workers is a list of *Workers
	workers map[string][]Worker

	//wg is used to help gracefully shutdown workers
	wg *sync.WaitGroup

	//PollRate the duration to Sleep each worker before checking the queue for jobs again
	//queue for jobs again.
	//Default: 500 milliseconds
	PollRate time.Duration
}```


and in the register method

```
	go func() {
		log.Printf("Starting up new worker...")
		var jobC jobChan
		for {
			// receive a notification from the queue chan
			select {
			case <-ctx.Done():
				log.Printf("Received signal to shutdown worker. Exiting.")
				q.wg.Done()
				return
			case jobC = <-q.notifier:
				lenWorker := len(q.workers[jobC.workerName])
				worker := q.workers[jobC.workerName][rand.Intn(lenWorker)]
				log.Printf("Receive job ID %d and picked up by worker %s", jobC.jobId, worker.ID())

				err := q.UpdateJobStatus(ctx, UpdateJobStatusParams{ID: jobC.jobId, Status: "RUNNING"})
				if err != nil {
					log.Printf("Unable to update job status: %s", err)
					continue
				}
				//If subsequent calls to updateJobStatus fail, the whole thing is probably hosed and
				//it should probably do something more drastic for error handling.
				job, err := q.GetJob(ctx, jobC.jobId)
				if err != nil {
					log.Printf("Error processing job: %s", err)
					q.UpdateJobStatus(ctx, UpdateJobStatusParams{ID: jobC.jobId, Status: "FAILED"})
					if err != nil {
						log.Printf("Error update status to failed for job: %s", err)
					}
					continue
				}
				// Call the worker func handling this job
				err = worker.DoWork(ctx, &job)
				if err != nil {
					log.Printf("Permanent error received from worker: %s", err)
					//permanent error, mark as failed
					q.UpdateJobStatus(ctx, UpdateJobStatusParams{ID: jobC.jobId, Status: "FAILED"})
				} else {
					q.UpdateJobStatus(ctx, UpdateJobStatusParams{ID: jobC.jobId, Status: "SUCCESS"})
				}
				log.Printf("Finished processing job %d", jobC.jobId)
			default:
				//log.Printf("Worker: %s. No message to queue. Sleeping 500ms", w.ID())
				time.Sleep(q.PollRate)
			}
		}
	}()
```
