### ISSUE TITLE
Does the job database continue to grow uncapped?

### ISSUE THREAD

**Issue by josegonzalez** [chiefnoah/goalpost#2]
I'm not super familiar with boltdb, but a cursory reading of the goalpost codebase does not show how I might truncate the database. My concern here is that the database can grow unbounded, even though a majority/all of the completed jobs are no longer relevant.

Thanks for the great project btw, hoping it can solve my needs/if it doesn't, that I'm capable enough to PR changes/fixes :)

**Comment by chiefnoah** [comment]
As of right now there's no easy way to truncate the database, and it will grow infinitely. A function to delete old jobs in the 'completed jobs' bucket is probably the best way to handle this generically. Simply looping through all the keys in that bucket then calling `Delete` on them should be sufficient.

**Comment by chiefnoah** [comment]
Hopefully that commit fixes your case, if not let me know and reopen this. I'm happy to take another stab at this, and PRs are welcome!
